/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  reflectisSidebar: [
      'Reflectis/intro',
      {
        type: 'category',
        label: 'Getting started',
        items: [
            {
                type: 'autogenerated',
                dirName: 'Reflectis/gettingstarted',
            }
        ],
      },
      {
        type: 'category',
        label: '3D Worlds',
        items: [
            {
                type: 'autogenerated',
                dirName: 'Reflectis/3dworld',
            }
        ],
      },
      'Reflectis/glossary',
      {
        type: 'category',
        label: 'Upgrade from 2024.3',
        items: [
            {
                type: 'autogenerated',
                dirName: 'Reflectis/upgradefrom20243',
            }
        ],
      },
  ],

  creatorkitSidebar: [
      'CK/intro',
      {
        type: 'category',
        label: 'Getting started',
        items: [
            {
                type: 'autogenerated',
                dirName: 'CK/gettingstarted',
            }
        ],
      },
      {
        type: 'category',
        label: 'Creator Kit components',
        items: [
            {
                type: 'autogenerated',
                dirName: 'CK/creatorkitcomponents',
            }
        ],
      },
      {
        type: 'category',
        label: 'Visual Scripting',
        items: [
            {
                type: 'autogenerated',
                dirName: 'CK/visualscripting',
            }
        ],
      },
      {
        type: 'category',
        label: 'Upgrade from 2024.3',
        items: [
            {
                type: 'autogenerated',
                dirName: 'CK/upgradefrom20243',
            }
        ],
      },
  ],
  
 boSidebar: [
     {
        type: 'autogenerated',
        dirName: 'Backoffice',
     },
  ],
};

export default sidebars;
