/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  creatorkitSidebar: [
      'CK/intro',
      {
        type: 'category',
        label: 'Getting started',
        items: [
            {
                type: 'autogenerated',
                dirName: 'CK/gettingstarted',
            }
        ],
      },
      {
        type: 'category',
        label: 'Creator Kit components',
        items: [
            {
                type: 'autogenerated',
                dirName: 'CK/creatorkitcomponents',
            }
        ],
      },
      {
        type: 'category',
        label: 'Visual Scripting',
        items: [
            {
                type: 'autogenerated',
                dirName: 'CK/visualscripting',
            }
        ],
      },
  ],
  
 boSidebar: [
    'Backoffice/boIntro',
     {
        type: 'category',
        label: 'Sezione 1',
        items: [
            {
                type: 'autogenerated',
                dirName: 'Backoffice/sezione1',
            }
        ],
      },
  ],
};

export default sidebars;
